### PR TITLE
add scoring system

### PR DESCRIPTION
**Pull request by alam3211**
So, here's the flow.... the player will keep choose the mode if they're winning,
all of the scores will be sum up and show up in the end of the game which is life = 0

### CODE REVIEW

**Comment by Shubham0812** [comment]
@alam3211 It will be better if the user selects the mode at the beginning of the game, and they play  the same mode until they lose, after which we can display the score.

**Comment by alam3211** [comment]
allright, gonna fix it soon bruh <3

**Comment by alam3211** [comment]
lets see if this fits you

**Comment by Shubham0812** [comment]
@alam3211  Merged, added name to contributors ! :D

**Pull request merged**
